name: CxJERP Security Tweets
# Controls when the workflow will run
on:
  workflow_dispatch: # *** this adds a run button ***
# Steps represent a sequence of tasks that will be executed as part of the job
permissions:
  contents: read
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Scan Iac with kics
    - name: Checkmarx DAST Github Action
      uses: Checkmarx/dast-github-action@v1.0.2
      env:
        CX_APIKEY: ${{ secrets.CX_APIKEY }}
      with:
        command: "web"
        config: './security_tweets.yaml'
        base_url: "https://deu.ast.checkmarx.net/"
        #environment_id: "08149bf3-dc33-4c35-a432-4fc476e274af"
        environment_id: "24e3b348-796d-4d80-9f49-45089ffbba28"
        #fail_on: "HIGH"
        verbose: true
        output: ./output
    - name: Reclaim output directory  
      if: always() 
      run: sudo chown -R 1001:1001 ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v3.0.2
      if: always()
      name: Upload Logs
      with:
        name: report
        path: ./output
